"""initial schema

Revision ID: 190b01228c37
Revises: 
Create Date: 2026-04-07 09:02:28.097881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import backend.models  # for UUIDType reference in autogenerated columns


# revision identifiers, used by Alembic.
revision: str = '190b01228c37'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', backend.models.UUIDType(length=36), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('razao_social', sa.String(length=255), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('score_vf', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('prioridade', sa.String(length=20), nullable=True),
    sa.Column('faixa_valor', sa.String(length=30), nullable=True),
    sa.Column('valor_aberto', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('qtd_inscricoes', sa.Integer(), nullable=True),
    sa.Column('anos_pgfn', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('ano_ult_inscricao', sa.Integer(), nullable=True),
    sa.Column('situacao_processual', sa.String(length=100), nullable=True),
    sa.Column('receita_principal', sa.String(length=100), nullable=True),
    sa.Column('simples_nacional', sa.Boolean(), nullable=True),
    sa.Column('frente', sa.Integer(), nullable=True),
    sa.Column('seguradora_elegivel', sa.String(length=50), nullable=True),
    sa.Column('responsavel', sa.String(length=20), nullable=True),
    sa.Column('estagio_pipeline', sa.String(length=50), nullable=True),
    sa.Column('data_entrada_estagio', sa.DateTime(), nullable=True),
    sa.Column('proximo_followup', sa.Date(), nullable=True),
    sa.Column('score_confirmado', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('limite_aprovado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('taxa_minima', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('pl', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('faturamento', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ebitda', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('regime_tributario', sa.String(length=50), nullable=True),
    sa.Column('porte', sa.String(length=30), nullable=True),
    sa.Column('capital_social', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('data_balanco', sa.Date(), nullable=True),
    sa.Column('decisor_nome', sa.String(length=100), nullable=True),
    sa.Column('decisor_cargo', sa.String(length=100), nullable=True),
    sa.Column('decisor_linkedin', sa.String(length=255), nullable=True),
    sa.Column('decisor_email', sa.String(length=100), nullable=True),
    sa.Column('decisor_email_confirmado', sa.Boolean(), nullable=True),
    sa.Column('decisor_telefone', sa.String(length=30), nullable=True),
    sa.Column('decisor_confianca', sa.String(length=10), nullable=True),
    sa.Column('decisor_validado', sa.Boolean(), nullable=True),
    sa.Column('valor_garantia', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('prazo_anos', sa.Integer(), nullable=True),
    sa.Column('taxa_negociada', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('premio_calculado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('honorarios', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('receita_vf', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status_proposta', sa.String(length=50), nullable=True),
    sa.Column('data_proposta', sa.Date(), nullable=True),
    sa.Column('numero_apolice', sa.String(length=50), nullable=True),
    sa.Column('data_emissao', sa.Date(), nullable=True),
    sa.Column('comissao_recebida', sa.Boolean(), nullable=True),
    sa.Column('honorarios_recebidos', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('enrichment_status', sa.String(length=30), nullable=True),
    sa.Column('situacao_cadastral_receita', sa.String(length=50), nullable=True),
    sa.Column('fallback_berkley', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('updated_by', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('metas',
    sa.Column('id', backend.models.UUIDType(length=36), nullable=False),
    sa.Column('responsavel', sa.String(length=20), nullable=False),
    sa.Column('periodo', sa.String(length=10), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('meta_valor', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('realizado_valor', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', backend.models.UUIDType(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('nome_completo', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('papel', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('consultas_seguradora',
    sa.Column('id', backend.models.UUIDType(length=36), nullable=False),
    sa.Column('company_id', backend.models.UUIDType(length=36), nullable=False),
    sa.Column('data_consulta', sa.DateTime(), nullable=True),
    sa.Column('seguradora', sa.String(length=50), nullable=True),
    sa.Column('modalidade', sa.String(length=100), nullable=True),
    sa.Column('limite_aprovado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('limite_disponivel', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('taxa', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('limite_judicial_pgfn', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('taxa_pct_anual', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('exige_mesa_credito', sa.Boolean(), nullable=True),
    sa.Column('exige_carta_nomeacao', sa.Boolean(), nullable=True),
    sa.Column('motivo_reprovacao', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('responsavel', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentos',
    sa.Column('id', backend.models.UUIDType(length=36), nullable=False),
    sa.Column('company_id', backend.models.UUIDType(length=36), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data_recebimento', sa.Date(), nullable=True),
    sa.Column('data_envio', sa.Date(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('responsavel', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inscricoes',
    sa.Column('id', backend.models.UUIDType(length=36), nullable=False),
    sa.Column('company_id', backend.models.UUIDType(length=36), nullable=False),
    sa.Column('numero_inscricao', sa.String(length=50), nullable=True),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('cnpj_raiz', sa.String(length=10), nullable=True),
    sa.Column('nome_devedor', sa.String(length=255), nullable=True),
    sa.Column('uf_devedor', sa.String(length=2), nullable=True),
    sa.Column('receita_principal', sa.String(length=100), nullable=True),
    sa.Column('valor_consolidado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('data_inscricao', sa.Date(), nullable=True),
    sa.Column('safra', sa.String(length=10), nullable=True),
    sa.Column('indicador_ajuizado', sa.String(length=5), nullable=True),
    sa.Column('tipo_situacao_inscricao', sa.String(length=100), nullable=True),
    sa.Column('situacao_inscricao', sa.String(length=100), nullable=True),
    sa.Column('tipo_garantia', sa.String(length=100), nullable=True),
    sa.Column('situacao_macro', sa.String(length=100), nullable=True),
    sa.Column('qtd_corresponsaveis', sa.Integer(), nullable=True),
    sa.Column('qtd_solidarios', sa.Integer(), nullable=True),
    sa.Column('tem_pf_corresponsavel', sa.Boolean(), nullable=True),
    sa.Column('unidade_responsavel', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_inscricao')
    )
    op.create_table('interactions',
    sa.Column('id', backend.models.UUIDType(length=36), nullable=False),
    sa.Column('company_id', backend.models.UUIDType(length=36), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('responsavel', sa.String(length=20), nullable=True),
    sa.Column('canal', sa.String(length=30), nullable=True),
    sa.Column('resumo', sa.Text(), nullable=True),
    sa.Column('proxima_acao', sa.Text(), nullable=True),
    sa.Column('estagio_anterior', sa.String(length=50), nullable=True),
    sa.Column('estagio_novo', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('propostas',
    sa.Column('id', backend.models.UUIDType(length=36), nullable=False),
    sa.Column('company_id', backend.models.UUIDType(length=36), nullable=False),
    sa.Column('numero_proposta', sa.String(length=50), nullable=True),
    sa.Column('valor_garantia', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('prazo_anos', sa.Integer(), nullable=True),
    sa.Column('taxa', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('premio_bruto', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('premio_liquido', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('comissao_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('comissao_valor', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('honorarios', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('receita_vf_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('flag_aderencia', sa.String(length=20), nullable=True),
    sa.Column('teto_percepcao', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('relacao_hon_premio', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status_proposta', sa.String(length=50), nullable=True),
    sa.Column('numero_apolice', sa.String(length=50), nullable=True),
    sa.Column('data_emissao', sa.Date(), nullable=True),
    sa.Column('comissao_recebida', sa.Boolean(), nullable=True),
    sa.Column('honorarios_recebidos', sa.Boolean(), nullable=True),
    sa.Column('nda_status', sa.String(length=30), nullable=True),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('updated_by', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('propostas')
    op.drop_table('interactions')
    op.drop_table('inscricoes')
    op.drop_table('documentos')
    op.drop_table('consultas_seguradora')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_table('metas')
    op.drop_table('companies')
    # ### end Alembic commands ###
